version: '3'

services:
  browse-scaler-cicd:
    image: browse-scaler:test-cicd
    build:
      context: ./
      dockerfile: Dockerfile.test
    volumes:
      - ./__test__:/app/artifacts
    command: npm run ci-test
    environment:
      - JEST_JUNIT_OUTPUT=./artifacts/junit.xml
