service: aws-python-project

frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: python3.8
  memorySize: 128 # default was 1024, 512 would also be accepted
  timeout: 5  # seconds
  environment:
    AWS_TEA_CONFIG_CMR: https://cmr.uat.earthdata.nasa.gov
    AWS_TEA_CONFIG_LOG_LEVEL: debug

package:
#  individually: true
  exclude:
    - node_modules/**

functions:
  hello:
    handler: handler.capabilities
    events:
      - http: GET ${self:custom.endPoint}/
      - http: GET ${self:custom.endPoint}/capabilities
  debug:
    handler: handler.debug
    events:
      - http: GET ${self:custom.endPoint}/debug
        request:
          parameters:
            querystrings:
              pretty=false
  status:
    handler: handler.health
    events:
      - http: GET ${self:custom.endPoint}/status
  provider:
    handler: handler.generate_tea_config
    events:
      - http: GET ${self:custom.endPoint}/provider/{id}

plugins:
  - serverless-python-requirements
  - serverless-s3-local
  - serverless-offline
custom:
  endPoint: /configuration/tea
  pythonRequirements:
    pythonBin: /usr/bin/python3
  s3:
    port: 7000
    host: localhost
    directory: ./build

resources:
  Resources:
    LocalBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: local-bucket
                
# aws --endpoint http://localhost:7000 s3 cp public/index.html s3://local-bucket/index.html --profile s3local