service: aws-python-project

frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: python3.8
  memorySize: 128 # default was 1024, 512 would also be accepted
  timeout: 15  # 7 seconds is the average run time currently
  environment:
    AWS_TEA_CONFIG_CMR: ${env:AWS_TEA_CONFIG_CMR, 'https://cmr.uat.earthdata.nasa.gov'}
    AWS_TEA_CONFIG_LOG_LEVEL: ${env:AWS_TEA_CONFIG_CMR, 'info'}

package:
#  individually: true
  exclude:
    - node_modules/**

functions:
  hello:
    handler: handler.capabilities
    events:
      - http: GET ${self:custom.endPoint}/
      - http: GET ${self:custom.endPoint}/capabilities
  status:
    handler: handler.health
    events:
      - http: GET ${self:custom.endPoint}/status
  provider:
    handler: handler.generate_tea_config
    events:
      - http: GET ${self:custom.endPoint}/provider/{id}

plugins:
  - serverless-python-requirements
  - serverless-offline
  - serverless-s3-local
custom:
  endPoint: /configuration/tea
  pythonRequirements:
    pythonBin: /usr/bin/python3
  # Prevent Serverless from attempting to modify the deployment bucket policy as
  # NGAP does not allow it
  deploymentBucket:
    skipPolicySetup: true