# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: graph-indexer
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  role: IamRoleGraphLambdaExecution
  deploymentBucket: graphdb-driver-deployment-bucket-${opt:stage}
  vpc:
    securityGroupIds:
      - ${cf:${opt:stage}.servicesSecurityGroupId}
    subnetIds: !Split [',', '${cf:${opt:stage}.subnetIds}']

plugins:
  - serverless-offline
  - serverless-pseudo-parameters

functions:
  index:
    handler: handler.index
    environment:
      ENVIRONMENT: ${opt:stage}
    events:
      - sqs:
          batchSize: 10
          arn: arn:aws:sqs:us-east-1:#{AWS::AccountId}:gsfc-eosdis-cmr-${opt:stage}-graphdb_queue

resources:
  Resources:
    IamRoleGraphLambdaExecution:
      Type: AWS::IAM::Role
      Properties:
        RoleName: cmrGraphRole-${opt:stage}
        PermissionsBoundary: arn:aws:iam::#{AWS::AccountId}:policy/NGAPShRoleBoundary
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: 'Allow'
              Principal:
                Service:
                  - 'lambda.amazonaws.com'
              Action:
                - 'sts:AssumeRole'
    cmrGraphPolicy:
      Type: AWS::IAM::Policy
      Properties:
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Action:
                - 'sqs:*'
              Effect: 'Allow'
              Resource: '*'
        PolicyName: cmrGraphPolicy-${opt:stage}
        Roles:
          - Ref: IamRoleGraphLambdaExecution
