name: CMR Checks
on:
  workflow_dispatch:
  push:
    branches: [ master, main, feature/**]
  pull_request:
    branches: [ master, main , features/**]
jobs:
  cloc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Remove non-CMR directories
        run: |
          rm -rf browse-scaler
          rm -rf legacy-migration
          rm -rf other
          rm -rf system-validation-test
          rm -rf tea-config-generator
          rm -rf token-service-client
      - name: Count Lines of Code (cloc)
        uses: djdefi/cloc-action@5
  kondo:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Run Kondo Report
        run: |
          docker run \
            --volume $PWD:/src \
            --rm cljkondo/clj-kondo \
            cd /src && \
            clj-kondo --parallel --lint \
              access-control-app/src \
              acl-lib/src \
              common-app-lib/src \
              common-lib/src \
              elastic-utils-lib/src \
              es-spatial-plugin/src \
              message-queue-lib/src \
            >> report.log
          cat report.log
        id: list-report
      - name: Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Kondo-Report.txt
          path: report.log
