service: graph-db

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  deploymentBucket: graphdb-driver-deployment-bucket-${self.stage}

deploymentBucket:
  skipPolicySetup: true

plugins:
  - serverless-offline

functions:
  bootstrapGremlinServer:
    handler: src/bootstrapGremlinServer/handler.bootstrap
    environment:
      CMR_ROOT: ${cf:${opt:stage}.servicesDnsName}
      GREMLIN_URL: ${cf:${opt:stage}.gremlinUrl}
      PAGE_SIZE: 2000
